### ISSUE TITLE
Small lag

### ISSUE THREAD

**Issue by elliotlings** [capaj/systemjs-hot-reloader#10]
Great tool, really easy to use!

I also previously tried https://github.com/geelen/jspm-server but prefer yours as it works with things like CSS too. 
I noticed, though, that jspm-server swaps the file almost instantly while jspm-hot-reloader has about a half second delay. I just wondered why this is the case?

**Comment by guybedford** [comment]
See https://github.com/capaj/jspm-hot-reloader/issues/18.

**Comment by elliotlings** [comment]
@guybedford great, thanks for investigating!

**Comment by capaj** [comment]
I think this was fixed now by 5f77835
Try it out, if not, let me know @elliotlings
