### ISSUE TITLE
Decouple from socket.io

### ISSUE THREAD

**Issue by Mosho1** [capaj/systemjs-hot-reloader#105]
I'm doing a small app with Electron, and successfully integrated systemjs with hot reloading, but I had to refactor out the code that deals with sockets in both the client and server scripts, and instead use a simple emitter to connect them rather than a socket, since in electron you can have the UI code and server code in the same runtime. I'd like to submit a PR that decouples the current code from socket.io, if it's something you think is desirable.

**Comment by capaj** [comment]
Definitely.

**Comment by alexisvincent** [comment]
@Mosho1 Checkout https://github.com/alexisvincent/systemjs-hmr, capaj/systemjs-hot-reloader should be switching to using this in the next few days or so. 

It provides HMR via a System.reload('some/module') extension.

Have a look at #107  to see how to use it.

**Comment by born2net** [comment]
is there anything different we need to do to our current setup yo use the new hmr? 
I am using angular2

regards

Sean

**Comment by alexisvincent** [comment]
@born2net please note, SystemJS-hmr is not suppost to be used by application developers. Sorry for that confusion. This project will transparently use it under the hood. The only issue will be if you use a lot of the internal hooks. If not you won't even notice the change

**Comment by born2net** [comment]
got it, tx...!

Sean
