### ISSUE TITLE
Repo jspm:systemjs-hot-reloader not found

### ISSUE THREAD

**Issue by FDiskas** [capaj/systemjs-hot-reloader#111]
```
$ jspm -v
0.16.47
```

**Comment by lancecarlson** [comment]
I have the same issue.

**Comment by capaj** [comment]
I just installed fine. I would suspect this will have something to do with your network or some error in JSPM's own repository resolution. Can you try again @FDiskas @lancecarlson ? Also can you try some other jspm package defined in https://github.com/jspm/registry/blob/master/registry.json ?

**Comment by lancecarlson** [comment]
$ jspm i --dev systemjs-hot-reloader

err  Repo jspm:systemjs-hot-reloader not found. Perhaps try jspm install npm:systemjs-hot-reloader.

warn Installation changes not saved.
[lcarlson@localhost ecp_example]$ jspm i --dev npm:systemjs-hot-reloader
     Looking up npm:systemjs-hot-reloader
     Downloading npm:systemjs-hot-reloader@0.6.0

warn Error on processPackageConfig
     Package.json dependency debug set to npm:debug@^2.2.0, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.
     To skip npm compatibility install with jspm install npm:systemjs-hot-reloader@0.6.0-o "{jspmPackage: true}".

warn Error processing package config for npm:systemjs-hot-reloader.

err  Error processing package config for npm:systemjs-hot-reloader.

warn Installation changes not saved.

**Comment by born2net** [comment]
so do we need to run hot-reload in a diff way now? with these changes?
I use it with Angular2
regards

Sean

**Comment by lancecarlson** [comment]
I've also tried on 4 different networks. Same issue.

**Comment by capaj** [comment]
@born2net no, it should still be usable as before. We haven't even released any new version. And even when 0.7.0 comes out, it won't change the way you use it.

**Comment by FDiskas** [comment]
'lodash' the same. `jspm install lodash`

**Comment by born2net** [comment]
great tx

**Comment by capaj** [comment]
@FDiskas the same problem when installing lodash? Well then it seems like a bug for @guybedford Maybe you could try some older version of JSPM in the meantime. I'd guess 0.16.30ish could be better

**Comment by lancecarlson** [comment]
@alexisvincent sorry, I've since moved on from this! Not sure if this is an issue anymore. :(

**Comment by alexisvincent** [comment]
Cool thanks
