### ISSUE TITLE
Publish ES5 code

### ISSUE THREAD

**Issue by Mosho1** [capaj/systemjs-hot-reloader#117]
I use systemjs without any transpilation, and installing the hot reloader forces me to install a transpiler (the only package to do so out of dozens).

**Comment by alexisvincent** [comment]
I agree, we should publish ES5. Will submit a PR tomorrow

**Comment by mpfau** [comment]
@alexisvincent are you still working on this?

**Comment by alexisvincent** [comment]
Will publish tonight
