### ISSUE TITLE
missing "next" files

### ISSUE THREAD

**Issue by unional** [capaj/systemjs-hot-reloader#119]
`jspm i --dev systemjs-hot-reloader` does not distribute `next/default-listener.js`.

https://github.com/capaj/systemjs-hot-reloader/blob/master/next/README.md#install

**Comment by alexisvincent** [comment]
Will have a look at why this is in an hour or two

**Comment by funn** [comment]
Because jspm when installs from github downloads latest realease which obviously doesn't include latest changes yet.

**Comment by alexisvincent** [comment]
@capaj If you're happy with the state of the project, do you want to release a major?

**Comment by alexisvincent** [comment]
Track major release in #124
