### ISSUE TITLE
Fix an issue when multiple files are changed at once

### ISSUE THREAD

**Issue by capaj** [capaj/systemjs-hot-reloader#14]
so that if multiple files are saved, we don't try to do too much at once.
if multiple files are saved, we should just remove all parts of the tree they affect and then just reload the root module

**Comment by doxavore** [comment]
This is particularly painful where you may be serving files (which may be transpiled, ngAnnotated, etc) from a temp folder, where there may be a slight delay, multiple events, or a .js and .html file both loaded via SystemJS that undergo separate compilation steps with indeterminate completion times.

Is there any workaround in the meantime, or a suggested plan for a PR that may be accepted?

**Comment by alexisvincent** [comment]
Tracking here -> https://github.com/alexisvincent/systemjs-hmr/issues/17
