### ISSUE TITLE
Remove backups

### ISSUE THREAD

**Issue by guybedford** [capaj/systemjs-hot-reloader#18]
The backups in https://github.com/capaj/jspm-hot-reloader/blob/master/jspm-hot-reloader.js#L132, take around 500ms. Removing this increases performance considerably from ~500ms to ~30ms in my tests.

**Comment by capaj** [comment]
soprry for response delay. My github notification have very nasty tendency of hiding the most important bits.
backups? that line is an ending bracket now, let me check what was that days ago.

**Comment by capaj** [comment]
Oh yeah those, thought that those would slow it down. Those are not needed for sure. Will remove them for next release.

**Comment by guybedford** [comment]
This is quite critical to land for performance reasons, and also related to #28.

I wouldn't suggest storing the dependency tree at all. There shouldn't have to be any risk involved in hot reloading that needs to be recovered from. The only part of state that needs to be retained is the original module objects only being disposed after hot reloading succeeds. Perhaps while a module is failing to reload, its original "successful" module load along with the initial state can be retained until the module successfully loads again?

**Comment by guybedford** [comment]
I guess reversion on failure is important here. To handle this without a deep clone could be done via storing metadata during the standard tracing removal process:

1. As we go through the tree of modules to remove them, add them to the "removed" backup list.
2. When there is a reimport failure, we go through the failed trees, restoring modules back with (`System.set(moduleName, backupModule)`), with the same dependency / binding respecting we do for the initial hot reloading.

Something along those lines sounds like it would work here.

Got my mind too full of npm interop workflows at the moment, so apologies to be issuing these points without tackling the full details head on, but it's best to get the ideas out and down here for reference.

**Comment by capaj** [comment]
@guybedford awesome. I plan to dive deep into it with full testing harness this weekend, so hopefully, we will get rid of that nasty clone there.

**Comment by capaj** [comment]
fixed by 5f77835

@guybedford I opted for easier path-just reimport root modules from last run. in the trival jspm-react sample, hot reload now takes around 50ms-60ms vs 250ms-300ms
