### ISSUE TITLE
Not yet solved usecase, please reload whole page

### ISSUE THREAD

**Issue by peteruithoven** [capaj/systemjs-hot-reloader#26]
When saving the same files quickly (by pressing cmd-s a couple of times) I get the `Not yet solved usecase, please reload whole page` error. 
It looks like the module that needs to be deleted and the module from System.get don't have exports for some reason.

**Comment by peteruithoven** [comment]
It looks like it goes wrong when a module is hot reloaded that doesn't have exports (yet). Could a file be partially written to disk, causing it not to have exports yet? 
I've tried adding a breakpoint in the `hotReload` function, in the `getModuleRecord` callback. It shows a difference. 
The file before it's reloaded properly:
![succes](https://cloud.githubusercontent.com/assets/523210/11527818/6228f38c-98e3-11e5-8c44-f50003920176.png)
The file before it will fail to import (throw the above mentioned error): 
![fail](https://cloud.githubusercontent.com/assets/523210/11527817/6218fb76-98e3-11e5-8b78-51784dc8d33c.png)

**Comment by peteruithoven** [comment]
It looks like different kind of objects. Tracing this back into getModuleRecord; the first (successfully loaded) one is retrieved from `System._loader.moduleRecords[normalizedName]`, the second one can't be and is retrieved from `System.loads[normalizedName]`. 
What could cause the same file to sometimes not show up in `System._loader.moduleRecords`?

**Comment by capaj** [comment]
@peteruithoven I thought this could have been mitigated by staging the hotreloads like I did here: https://github.com/capaj/jspm-hot-reloader/blob/master/jspm-hot-reloader.js#L52

Will have to repro it again and debug that. Optimistically I could get to it next weekend. Pesimistically 20th of January :-(

**Comment by peteruithoven** [comment]
Ah alright. Btw, I can only reproduce this in a bigger project I'm working on, when I create a basic example I can't reproduce the problem.

**Comment by capaj** [comment]
Don't worry I have two big projects where I think I will be able to
reproduce it.

J.Š
Dne 2. 12. 2015 12:56 napsal uživatel "Peter Uithoven" <
notifications@github.com>:

**Comment by capaj** [comment]
@peteruithoven In the last version I don't care about reconstructing the tree at all- I just reimport whichever root modules were found before failed reimport so it is quite possible this might not be occurring anymore. Can you confirm this still occurs even with version > 0.5.0 on your project @peteruithoven ?

**Comment by peteruithoven** [comment]
I'll check. Thanks for the improvements!

**Comment by peteruithoven** [comment]
Very nice, problem seems solved.
