### ISSUE TITLE
Error when trying to clone the uncloneable

### ISSUE THREAD

**Issue by teohhanhui** [capaj/systemjs-hot-reloader#28]
`TypeError: Illegal invocation` is thrown here:
https://github.com/lodash/lodash/blob/10f9c3ae14c45c16dcf3d8b0aa1a1bf0857ac508/lodash._basefor/index.js#L40

called from:
https://github.com/capaj/jspm-hot-reloader/blob/7c100500c88d2e6cd658dd25c8855b3aab4352d0/jspm-hot-reloader.js#L144

When trying to clone [`global/document`](https://github.com/Raynos/global/blob/e180fd872bee995586238a46da8f2c8889b6904c/document.js) which is the `document` object, which of course is not cloneable...

**Comment by capaj** [comment]
@teohhanhui thanks. The cloning is not really needed. I will try to find better ways to to store current dependency tree in memory. Any ideas would be greatly appreciated.

**Comment by capaj** [comment]
fixed by 5f77835
