### ISSUE TITLE
all reimported

### ISSUE THREAD

**Issue by happylinks** [capaj/systemjs-hot-reloader#29]
Hi,

I'm trying to integrate this in my backbone.js project. But whenever I make a change, all the files up until the "main" file are reimported. I would like to only reload the one I changed, but maybe I'm misunderstanding the hot reloader.

My log:
```
deleted a module  http://localhost:8080/src/modules/clubs/routes/list/views/item.js  because it has dependency on  origin
jspm-hot-reloader.js:105 deleted a module  http://localhost:8080/src/modules/clubs/routes/list/views/collection.js  because it has dependency on  http://localhost:8080/src/modules/clubs/routes/list/views/item.js
jspm-hot-reloader.js:105 deleted a module  http://localhost:8080/src/modules/clubs/routes/list/route.js  because it has dependency on  http://localhost:8080/src/modules/clubs/routes/list/views/collection.js
jspm-hot-reloader.js:105 deleted a module  http://localhost:8080/src/modules/clubs/controller.js  because it has dependency on  http://localhost:8080/src/modules/clubs/routes/list/route.js
jspm-hot-reloader.js:105 deleted a module  http://localhost:8080/src/router.js  because it has dependency on  http://localhost:8080/src/modules/clubs/controller.js
jspm-hot-reloader.js:105 deleted a module  http://localhost:8080/src/index.js  because it has dependency on  http://localhost:8080/src/router.js
jspm-hot-reloader.js:167 toReimport ["http://localhost:8080/src/index.js"]
```

Any help would be appreciated.

**Comment by peteruithoven** [comment]
Also see: https://github.com/capaj/systemjs-hot-reloader/issues/22
The tricky thing is that it can't change references to the module you want to reload, so it also needs to reload modules with those references. If you know of a solution that would be great.

**Comment by happylinks** [comment]
Ah I kinda get it now. I was having issues because Backbone.history was restarted, and that caused the entire frontend to stop working. After fixing that the reloading worked fine.
I finally got the reloading working and I love it :) Way better than having to wait for a 12 sec reload every time.
