### ISSUE TITLE
Use trace API

### ISSUE THREAD

**Issue by guybedford** [capaj/systemjs-hot-reloader#3]
Good point about the ES5 modules not being tracked. They are stored on `loader.defined` originally but this is cleared out after execution to save memory. We keep `moduleRecords` around only because ES modules need the tree information to propagate bindings.

Setting `System.trace = true` will give all the trace info you need at https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/tracing-api.md.

**Comment by capaj** [comment]
@guybedford another great suggestion. I as mildly aware about trace api as some other libraries use it. Will implement that soon.

**Comment by capaj** [comment]
@guybedford but even with this,  I don't get the importers. I need importers, because I need to climb the tree up from the changed module. Could we add importers to the properties, right next to depMap and deps?

I could try to implement it with searching-on any module change I will iterate the whole tree and find any importers of changed modules.
This will probably get slow for big projects, but it could be allright for small to medium.

**Comment by capaj** [comment]
for now I will populate importers like this, that should be sufficent:
```
Object.keys(System.loads).forEach((moduleName) => {
      let mod = System.loads[moduleName]
      mod.deps.forEach((dependantName) => {
        let normalizedDependantName = mod.depMap[dependantName]
        let dependantMod = System.loads[normalizedDependantName]
        if (!dependantMod.importers) {
          dependantMod.importers = []
        }
        dependantMod.importers.push(moduleName)
      })
    })
```

Though I am not sure how fast it will be for apps with thousands of dependencies.

**Comment by guybedford** [comment]
That looks fine to me. It is just graph traversal, so of order of the number of nodes, which isn't a performance issue, especially if you only have to run this once for each tree (and also when a given tree is refreshed by hot reloading in turn I assume?).

I'd suggest adding a stop condition for circular references if you can, perhaps via a flag to track that you've already populated the importers of a given dependency.

**Comment by alexisvincent** [comment]
Closing since this is now handled in `systemjs-hmr`
