### ISSUE TITLE
System._loader.moduleRecords doesn't contain .jst/.json files.

### ISSUE THREAD

**Issue by happylinks** [capaj/systemjs-hot-reloader#31]
I'm trying to do a reload when my templates (.jst) change. They don't seem to be in moduleRecords, they are however in System._loader.modules. But System.delete only deletes from moduleRecords.

Does anybody know why the .jst files are in .modules, but not in .moduleRecords?

The modulename from one template is resolved to:
http://localhost:8080/src/modules/auth/templates/register/base.jst!http://localhost:8080/jspm_packages/github/podio/plugin-jst@0.1.2.js

**Comment by capaj** [comment]
@happylinks that is how the loader plugins work. SystemJS being a shim of system-loader spec, it stores ES6 modules in moduleRecords and the rest in `System._loader.modules`. 
I haven't really tested HotReloader with plugins yet. I will try that.
Which loader plugin for `.jst` are you using?

**Comment by happylinks** [comment]
Hi, I'm using this one: https://github.com/podio/plugin-jst
Ok, do you know if there is another way to "System.delete" a source that is not in moduleRecords?

**Comment by capaj** [comment]
@guybedford would definitely know.

I have been looking at plugins before, like 3/4 months ago. I don't remember exactly how it ended. I was trying to make commonJS modules work with hot reloader. They are stored in `System._loader.modules` as well.

**Comment by guybedford** [comment]
For plugins that are configured via meta configuration, these should work completely fine in the hot reloader today.

For example, the CSS plugin can provide an `__unload` export method for every CSS file, which would remove the CSS, before the new CSS is injected allowing CSS hot reloading.

So I believe it's just plugins via syntax that would need special support here.

In order to handle that, given the normalized module name being hot reloaded (`http://path/to/module.js`), we just then include iteration of the entire registry to find any modules of the form `http://path/to/module.js!*`. Those modules should then all be hot reloaded as well.

I think that should cover the use cases, but let me know if I have missed anything here.

**Comment by guybedford** [comment]
Note that plugins via syntax is something that is being deprecated though, so I'd almost be happier if this wasn't supported to encourage the configuration style.

**Comment by guybedford** [comment]
(It's not being explicitly deprecated, it's just being discouraged)

**Comment by capaj** [comment]
@guybedford thanks! Gonna try CSS modules first. Is there any example with css loader being configured via meta configuration? Would love to try it out.

**Comment by guybedford** [comment]
@capaj sure, it would just be via the standard workflow like in https://github.com/systemjs/systemjs/blob/master/docs/overview.md#basic-use. Happy to integrate an `__unload` method into https://github.com/systemjs/plugin-css/blob/master/css.js too if you want to try a simple use case.

**Comment by capaj** [comment]
@guybedford yeah, I always keep forgetting about systemjs docs. Sorry!
I will try to integrate __unload into css plugin and open a PR if you don't get to it before me.

**Comment by happylinks** [comment]
I'll look into this for jst templates. Or is that what you mean with "plugins via syntax". Or just plugins that aren't loaded via meta configuration?
Thanks for the quick reactions!

**Comment by guybedford** [comment]
@happylinks yes exactly, it should work for `jst` templates as well (in theory!), so do post back if you see any issues.

**Comment by happylinks** [comment]
Hey, I've been trying to fix this today but I don't seem to be making progress.
Couple of questions:
I've followed https://github.com/systemjs/systemjs/blob/master/docs/overview.md#basic-use to set up the plugin using the meta-config. In this example it seems as if I don't need to use the ! at the end of the import path to be able to import the file. I can't get this working at all, it always adds the .js at the end when trying to import.
Is this a documentation error or should it really be possible to not use the "!" ?
When I do add the ! the file is loaded correctly, but then I don't need the meta configuration so I think the hot reloading won't work then, because the file gets loaded in System._loader.modules instead of Sytem._loader.moduleRecords.
I also tried this with the json plugin but got the same results.

Can you give me some pointers? I would love to fix this!

**Comment by happylinks** [comment]
Ok, got a little farther.
```System.delete("http://localhost:8080/src/modules/users/routes/show_admin/templates/header.jst!http://localhost:8080/jspm_packages/github/podio/plugin-jst@0.1.2.js")
true
System.import("http://localhost:8080/src/modules/users/routes/show_admin/templates/header.jst!http://localhost:8080/jspm_packages/github/podio/plugin-jst@0.1.2.js")
lib$es6$promise$promise$$Promise {_id: 294, _state: undefined, _result: undefined, _subscribers: Array[0]}
```
I'll see where this gets me!

**Comment by happylinks** [comment]
I'm close!
When I run
```
System.delete("http://localhost:8080/src/modules/activities/templates/layout.jst!http://localhost:8080/jspm_packages/github/podio/plugin-jst@0.1.2.js")
```
and then 
```
System.import("http://localhost:8080/src/modules/activities/templates/layout.jst!http://localhost:8080/jspm_packages/github/podio/plugin-jst@0.1.2.js").then(source => {console.log(source)});
```
It loads the new template.

**Comment by happylinks** [comment]
Mm nope, didn't work.
I got as far as reloading the template.
System.delete works fine for the templates with "!".
I disabled the check at https://github.com/capaj/systemjs-hot-reloader/blob/master/hot-reloader.js#L170 so it would add the templates to the reload-list and call System.import again. But this caused the following problem: there is no importers list for these templates. So the modules that reference the template don't get reloaded as wel, so they won't have the new template.

I'm not sure if I did the loading of the templates ok with the meta configuration and stuff, but they don't go in the moduleRecords, and because of that I think that they don't contain the information to make a successful hotreload.

**Comment by guybedford** [comment]
@happylinks perhaps try using a config along the lines of the following to avoid extensions:

```javascript
System.config({
  packages: {
    'src/modules/activities': {
      meta {
        '*.jst': { loader: 'path/to/jst-loader-name' }
      }
    }
  }
});
```

**Comment by happylinks** [comment]
Yeah! that works, thanks! I'll try to see if I can get any further with the hot reloading now :+1:

**Comment by happylinks** [comment]
IT WORKS! Thank you so much, my templates are hot reloading perfectly now.
I used this config to be able to remove the "!" from the imports:
```
packages: {
    "src": {
      "meta": {
        "*.jst": {
          "loader": "jst"
        },
        "*.json": {
          "loader": "json"
        }
      }
    }
  },
```

And in my main javascript file i have the __reload which reload the current route (with the fresh templates).
```
export function __reload(deletedModule) {
  setTimeout(function() {
    NavigationService.reload();
  }, 100);
}
```
It has a small timeout because it seems sometimes not all templates/files are loaded yet before the __reload is called.

Thanks for your feedback!

**Comment by peteruithoven** [comment]
@guybedford in comment https://github.com/capaj/systemjs-hot-reloader/issues/31#issuecomment-167436950 you're missing a `:` behind `meta`.

**Comment by capaj** [comment]
@peteruithoven fixed so that people don't get syntax errors when copy pasting
