### ISSUE TITLE
Cannot import systemjs-hot-reloader (weakee/Emitter is undefined)

### ISSUE THREAD

**Issue by oinksoft** [capaj/systemjs-hot-reloader#33]
With 0.5.1 I get:

```
Potentially unhandled rejection [2] TypeError: Error evaluating github:capaj/systemjs-hot-reloader@0.5.1/hot-reloader
Super expression must either be null or a function, not undefined
    at exports.default (http://localhost/jspm_packages/npm/babel-runtime@5.8.20/helpers/inherits.js:7:11)
    at eval (http://localhost/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1/hot-reloader.js!eval:36:9)
    at execute (http://localhost/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1/hot-reloader.js!eval:272:9)
    at t (http://localhost/jspm_packages/es6-module-loader.js:7:19798)
    at v (http://localhost/jspm_packages/es6-module-loader.js:7:20180)
    at v (http://localhost/jspm_packages/es6-module-loader.js:7:20027)
    at u (http://localhost/jspm_packages/es6-module-loader.js:7:19856)
    at s (http://localhost/jspm_packages/es6-module-loader.js:7:19737)
    at http://localhost/jspm_packages/es6-module-loader.js:7:22064
    at O (http://localhost/jspm_packages/es6-module-loader.js:7:7439)
```

I found the super() TypeError is coming from

```js
class HotReloader extends Emitter {
```

`Emitter` is undefined. As far as I can tell, I'm getting this error with a canonical setup (based on what's in the README and some of the examples). Is there some problem with weakee, or maybe some setup step that isn't in the docs?

**Comment by oinksoft** [comment]
Forgot to mention that this happens when trying to import the hot reloader:

```html
<script src="/jspm_packages/system.js"></script>
<script src="/jspm-config.js"></script>
<script>
  System.trace = true;
  System.import('capaj/systemjs-hot-reloader');
</script>
```

**Comment by capaj** [comment]
@oinksoft what version of JSPM are u running?

**Comment by peteruithoven** [comment]
The weakee package is installed? (This should happen automatically with installing the systemjs-hot-reloader). You can check if a `/jspm_packages/npm/weakee...` folder exists.

**Comment by oinksoft** [comment]
@capaj I'm running JSPM 0.15.7.

@peteruithoven The weakee package was installed, it shows up in the right places in jspm-config and can be imported with its unaliased name. It seems like only hot-reloader.js gets `undefined` for this module.

**Comment by oinksoft** [comment]
@peteruithoven If it weren't installed correctly, I believe there would be a 404 on the script URL and an "Error loading" message from SystemJS. Earlier I was able to see `console.log` statements that I added to weakee.js, so this file is definitely being loaded.

**Comment by capaj** [comment]
@oinksoft try updating to jspm 0.16.15 or newer and let me know if that fixes it.
I think I have had an issue from one guy with weakee problems who solved it like this.

**Comment by oinksoft** [comment]
@capaj Interesting, I had the same error with JSPM 0.16.18 but it seems to be working with 0.6.15 so I'll use that.

**Comment by capaj** [comment]
@oinksoft I just did a jspm install into clean repo and it worked even with 0.16.18 JSPM.
Well, anyway, closing this, because this is not an issue I can solve.
