### ISSUE TITLE
Number of initial requests

### ISSUE THREAD

**Issue by mpfau** [capaj/systemjs-hot-reloader#39]
When I include `System.import('capaj/systemjs-hot-reloader')`, the number of requests during initial page load increases above 100 (core-js and babel-runtime).

I tried to create a bundle with the hot reloader and all dependencies (`jspm bundle capaj/systemjs-hot-reloader build/hr.js --inject`). Unfortunately, the bundle is not picked up and all core-js and babel-runtime modules are loaded on their own (not from the bundle). 

Any idea why this does not work?

**Comment by peteruithoven** [comment]
I've extended my dependencies bundle with the hot reloader, which seems to work. I use the following command: 
```
jspm bundle 'js/**/* - [js/**/*] + capaj/systemjs-hot-reloader' bundle.js --inject
```
Is there anything out of the ordinary in the jspm bundle response? Anything that's not listed that you think should be listed etc.

**Comment by mpfau** [comment]
@peteruithoven jspm bundle response was just as normal. I resetted my working copy (`rm -r jspm_packages/ node_modules/`and `npm i`) after I could not reproduce this on another dev machine. Everything works as expected now, thanks!
