### ISSUE TITLE
Enable use without trace: true

### ISSUE THREAD

**Issue by guybedford** [capaj/systemjs-hot-reloader#45]
All modules run through the register handler of SystemJS, so it should be fully possible to make this work without having to set trace: true on SystemJS.

Basically `System._loader.moduleRecords` contains the SystemJS private tree which should contain the same information as `System.loads` I believe?

If it is lacking we can certainly look at adjusting this as the trace: true feature will be deprecated in the next release of SystemJS.

**Comment by guybedford** [comment]
(by next release I mean the major deprecation release later this year)

**Comment by capaj** [comment]
ok, I will have a look at that.
Seems like rewriting those two lines should do it: https://github.com/capaj/systemjs-hot-reloader/search?utf8=%E2%9C%93&q=System.loads

**Comment by alexisvincent** [comment]
Handling this in `systemjs-hmr`, although I don't think usage without trace is possible here
