### ISSUE TITLE
Configure systemjs-hot-reloader with Browsersync ?

### ISSUE THREAD

**Issue by jingignoli** [capaj/systemjs-hot-reloader#46]
Hi,

It's not an issue but i don't understand how to configure the systemjs-hot-reloader in my jspm configuration.

I'm using Browsersync to serve my files (npm, jspm, TypeScript, angular 2, Browsersync)
Browsersync is launched by a npm scripts 

Can you give me some help ?
jspm is wonderful but without hot reloading in dev mode it's too long ...

Thanks,

Julie.

**Comment by capaj** [comment]
I think using browsersync with systemjs-hot-reloader might not be the best idea-both watch your files for changes. There is certainly a clash of responsibilities there. You certainly can make it work-you would have to disable browsersync whole page reload for all `ts` files and then run https://github.com/capaj/chokidar-socket-emitter in the folder to feed the file changes into HotReloader.

If I had spare time, I would prepare a solution with everything set up, unfortunately I don't have :disappointed:

**Comment by peteruithoven** [comment]
I currenly use the following script, which combines chokidar and http-server:
```
'use strict';
const httpServer = require('http-server');
const server = httpServer.createServer({
  cache: -1,
  robots: true,
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Credentials': 'true'
  }
});

require('chokidar-socket-emitter')({
  app: server.server,
  chokidar: {
    ignored: [/[\/\\]\./, 'node_modules/**', 'jspm_packages/**']
  }
});

server.listen(3000);

console.log('Visit: localhost:3000');
```
You can more easily start this adding `nodejs server` in your package.json's start script and/or Makefile.

**Comment by jingignoli** [comment]
@capaj thanks for your answer, i will forgot this idea for the moment :-)

@peteruithoven, yes i see this sample thanks !

**Comment by peteruithoven** [comment]
This new project also seems very interesting: https://github.com/mikz/jspm-dev-server

**Comment by amcdnl** [comment]
would love to see browsersync integration too. I have a feeling you could almost bypass the chokidar-socket-emitter w/ BS too.

**Comment by Quirksmode** [comment]
Might be worth checking https://github.com/angularclass/NG6-starter/tree/jspm. This seems to have BrowserSync working with a Hot Reloader

**Comment by amcdnl** [comment]
@Quirksmode That project doesn't work :(

I got a rough draft using browser sync by itself - https://gist.github.com/amcdnl/19904a939b3be3e8bc5d

Sadly, I have issues with Angular 1.x and reloading but everything else works :) !

**Comment by Quirksmode** [comment]
Sorry to hear that it didn't work :-( Keep me posted if you mange to solve Angular 1.x as this is something we are also looking to implement.

**Comment by amcdnl** [comment]
@Quirksmode well, I can make it work but its not worth it. There is no way to un-register angular modules so you have to tear down the whole app.  When you tear down the app and re-bootstrap some things don't get loaded correctly. At that point, you might as well just refresh :S

**Comment by peteruithoven** [comment]
Could we keep this issue focused on combining browsersync with the hot reloader?

**Comment by amcdnl** [comment]
@peteruithoven don't be a troll. I was just explaining why that didn't work for me. my above code does solve the problem abstractly speaking.

**Comment by JordanBelford** [comment]
@amcdnl @Quirksmode I fixed the NG6-Starter project with [this pull request ](https://github.com/AngularClass/NG6-starter/pull/107). It is a good example of browsersync + systemjs-hot-reloader. 

Like @capaj said, you want to be careful with clashing responsibilities since they both watch your files. NG6-Starter is set up so browsersync watches html and css, and the hot-reloader watches js. 
For my use case, I am using systemjs-hot-reloader for reloading js and html, and browsersync for css.

**Comment by amcdnl** [comment]
@JordanBelford Awesome! My example replaces this project since now that I have BS listening to file changes and sending socket events, all u need to do is listen to those events and then have system reload :).

**Comment by peteruithoven** [comment]
Another very easy way to combine them is using npm scripts: 
``` json
  "scripts": {
    "start": "npm run serve & npm run watch",
    "serve": "browser-sync start --server --files='**, !jspm_packages, !node_modules'",
    "watch": "chokidar-socket-emitter -l 5776"
  },
```
https://css-tricks.com/why-npm-scripts/
http://www.jayway.com/2014/03/28/running-scripts-with-npm/

**Comment by ArmorDarks** [comment]
So, you mean to start to parallel watching processes?

I wonder, can hot-reloader work with Browser Sync without need to spawn additional processes?

**Comment by alexisvincent** [comment]
@jingignoli can I close this?

**Comment by jingignoli** [comment]
Yes we can
