### ISSUE TITLE
Hot reload HTML

### ISSUE THREAD

**Issue by JordanBelford** [capaj/systemjs-hot-reloader#50]
It would be awesome if this worked for html files as well. 

In my app, I am importing html files with the !text plugin. I have an idea for implementing it, but I need to be able to find the parent module that imported the html file. The hot reloader seems to be using System._loader.moduleRecords to find the module hierarchy for js files. 

Does anyone with more internal SystemJs knowledge know where I can find the module that imported an html file? @capaj @guybedford 

I can see the full module name in System._loader.modules, but can't seem to find the hierarchy.

**Comment by CaptainN** [comment]
Editing HTML did work in my limited testing (after basically following the simple tutorial to set this up).

**Comment by capaj** [comment]
@JordanBelford please see https://github.com/capaj/systemjs-hot-reloader/issues/74#issuecomment-221845425

Closing for now, if it still doesn't work, let me know.
