### ISSUE TITLE
Handlebars

### ISSUE THREAD

**Issue by ineentho** [capaj/systemjs-hot-reloader#58]
Handlebars (`import './template.hbs!'`) did not work out of the box, but I managed to fix it with a 1 line change. I'm not fully aware of how the JSPM internals work, so I'm not sure if I broke something in the process:

I changed [line 141](https://github.com/capaj/systemjs-hot-reloader/blob/d2c1589beb287eae93131ad73c303b929f73c7e8/hot-reloader.js#L141) from

```
let aModule = System._loader.moduleRecords[normalizedName]
```

to

```
System.loads[normalizedName]
```

Is that a change that should be merged into hot reloader?

**Comment by capaj** [comment]
@ineentho I think very few people are aware of how JSPM internals work. I am not sure whether it is valid to use `System.loads[normalizedName]` instead `System._loader.moduleRecords[normalizedName]`, but I think I wanted to ask the same thing @guybedford at some point.

Certainly will try it out on my bigger project and if it works fine, will merge it.

**Comment by happylinks** [comment]
Hi,
Maybe try it with meta config, in your config.js use this:
```
packages: {
    "src": { // use the folder of your templates here
      "meta": {
        "*.hbs": {
          "loader": "hbs" // Use the plugin name here (maybe plugin-hbs?)
        },
      }
    }
  },
```
Then include your handlebar templates without the ! at the end.
```
import './template.hbs'
```

**Comment by capaj** [comment]
@happylinks good advice. Going forward meta configs are preffered over `!` notation, that much I know.

**Comment by ineentho** [comment]
@happylinks @capaj When did meta configs get preferred over ! syntax? The systemjs readme still suggests that you use !. I maybe should try changing to use meta loader and see if something else breaks.

**Comment by capaj** [comment]
@ineentho since jspm 0.17.0, but `!` will not be deprecated soon. Feel free to use it if it suits you better.

**Comment by happylinks** [comment]
I had the same problem with jst templates, and asked guybedford. see: https://github.com/capaj/systemjs-hot-reloader/issues/31
So I think hotreloading should be done with the meta-config for now.

**Comment by alexisvincent** [comment]
Resolved :)
