### ISSUE TITLE
Hot reloading not working with temlateUrl in angularjs2

### ISSUE THREAD

**Issue by zbindenren** [capaj/systemjs-hot-reloader#62]
I took [MarioBrendel/Angular2-Jspm-Typescript-Atom-Seed](https://github.com/MarioBrendel/Angular2-Jspm-Typescript-Atom-Seed.git) and changed it in order to use `templateUrl` for html templates instead of inline templating  ([see my fork here](https://github.com/zbindenren/Angular2-Jspm-Typescript-Atom-Seed.git)).

When I change the `app.component.html` the change is detected, but the content is not reloaded. When I change the `app.component.ts` file, the previous changes in `app.component.html` are reloaded.

Any ideas?

**Comment by jonricaurte** [comment]
@zbindenren are you using meta tags?

https://github.com/capaj/systemjs-hot-reloader/issues/74#issuecomment-205845387

**Comment by svi3c** [comment]
@zbindenren Why are you using `templateUrl`? As long as you do not directly import the template, SystemJS will not know about a module to reload.
You might consider loading it via plugin-text https://github.com/systemjs/plugin-text and have a look at https://github.com/capaj/systemjs-hot-reloader/issues/74.

**Comment by zbindenren** [comment]
Thanks, closing the issue.
