### ISSUE TITLE
Can't install socket.io dependency

### ISSUE THREAD

**Issue by screendriver** [capaj/systemjs-hot-reloader#68]
I followed the instructions in the [jspm 0.17 Beta Guide](http://jspm.io/0.17-beta-guide/hot-reloading.html) that was written by @guybedford himself but I get following warning

``` sh
❯ jspm install --dev systemjs-hot-reloader
     Updating registry cache...
     Downloading github:socketio/socket.io-client@1.4.5

warn github:socketio/socket.io-client@1.4.5 dependency installs skipped as it's a GitHub package
     with no registry property set.
     If the dependencies aren't needed ignore this message. Alternatively set a registry or
     dependencies override or use the npm registry version at jspm install
     npm:socket.io-client@^1.4.5 instead.

ok   Installed github:socketio/socket.io-client@^1.4.4 (1.4.5)
ok   Dev dependency systemjs-hot-reloader to github:capaj/systemjs-hot-reloader@^0.5.6 (0.5.6)
     Install tree has no forks.

ok   Install complete.
```

If I make a `chokidar-socket-emitter` later on the tutorial my browser does an endless loading and never stops. I think this has something to do with the warning above.

**Comment by guybedford** [comment]
I think this install is right - the dependency installs are supposed to be skipped. I suspect it would be something else behind it.

**Comment by screendriver** [comment]
Then I don't know whats going on. I copied and pasted everything from your tutorial but my Browsers is loading endless.

**Comment by capaj** [comment]
@screendriver do you have any errors in the console?

**Comment by guybedford** [comment]
@screendriver make sure you're running the latest version of `chokidar-socket-emitter` perhaps?

**Comment by screendriver** [comment]
I am using `0.5.0`. My project is 10 minutes old so all dependencies should be at the latest version. My browser shows me only a white window and the loading indicator is spinning. No errors on my console. It looks like that the webserver is not sending any response (and no timeout) and is waiting for something.

**Comment by guybedford** [comment]
If you're only getting a white window, then that is unrelated to hot reloading, which will apply for the second render. Perhaps go back a step in the tutorial and confirm if the first render is working ok.

**Comment by screendriver** [comment]
Do you mean?

> Open up test.html through a local server or a file URL and that's it.

That's working. I used [Browsersync](https://www.browsersync.io) for that and I saw `Hello World`. After that I followed the steps in chapter 2 step by step (copy and paste).

**Comment by alexisvincent** [comment]
@screendriver still an issue?

**Comment by screendriver** [comment]
I don't use `jspm` / `SystemJS` anymore

**Comment by alexisvincent** [comment]
Tooling issue?

**Comment by screendriver** [comment]
Yes. Switched to `webpack`.

**Comment by alexisvincent** [comment]
Yeah, this ecosystem really needs to get more beginner friendly. Also a lack of tooling :/ Goodluck :)
