### ISSUE TITLE
“Even Dan Abramov admitted himself reloading whole modules and rerendering is the way to go.”

### ISSUE THREAD

**Issue by gaearon** [capaj/systemjs-hot-reloader#69]
This is not the correct takeaway from my article. This is basically taking two paragraphs from it and putting them outside the context :wink: 

Reloading whole modules and re-rendering works great **if you keep all your state in a single store and don’t care about killing the DOM**. While this may be the case for some people, I claim that overwhelming majority of complex apps that would benefit from hot reloading

* don’t keep their state in a single store
* actually would suffer from killing the DOM due to reset of scroll position, inputs, etc

I would like to ask you to change the wording so it doesn’t suggest a conclusion that I never reached.
Thanks!

**Comment by capaj** [comment]
@gaearon thanks for opening this. Fixed in the latest commit.

**Comment by gaearon** [comment]
Thank you! :+1:
