### ISSUE TITLE
Bundled error: System is not defined 

### ISSUE THREAD

**Issue by peteruithoven** [capaj/systemjs-hot-reloader#70]
When bundling using `bundle-sfx` and importing the default-listener.js I'm getting the error: 
```
Uncaught ReferenceError: System is not defined
```
From: hot-reloader.js:9

What's the best way to solve this? Is there a way to autmatically exclude it when bundling to a sfx? I was trying this to reduce the boilerplate of using the following method: https://github.com/capaj/systemjs-hot-reloader#connect-to-custom-event-emitter-port

**Comment by peteruithoven** [comment]
Importing the default loader in my html seems like the simples solution for now
``` html
    <script type="text/javascript">
      System.trace = true;
      System.import('capaj/systemjs-hot-reloader/default-listener.js');
      System.import('./js/index.js');
    </script>
```
To clarify why this gets ignored when bundling; I'm also processing the html file with:
```
html-dist index.html --minify  --remove-all --insert app.js -o dist/index.html
```

**Comment by peteruithoven** [comment]
Because I'm curious for simpler solutions I'd like to keep this issue open for a short while longer.

**Comment by guybedford** [comment]
@peteruithoven in jspm 0.17 the package config at https://github.com/capaj/systemjs-hot-reloader/blob/master/package.json#L49 makes sure this is not included when running `jspm build --production`.

**Comment by peteruithoven** [comment]
Very nice! Thanks.
