### ISSUE TITLE
Import error breaks the reloading

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [capaj/systemjs-hot-reloader#75]
When import fails:
`import NonExistent from './nonexistent-file.js'`
module cannot recover. Saving it with:
`import Existent from './existent-file.js'`
continues to throw the same "file not found" error (and nothing else updates). It's essentially stuck =/

Hot-reloader Version: 0.5.6
JSPM Version: 0.17.0-beta.13

**Comment by capaj** [comment]
@m-a-r-c-e-l-i-n-o thanks for this bug. I knew it was there, but forgot to address it. I tried it yesterday and I think I might have a remedy. It basically consists of deleting modules again after a failed reimport. It shouldn't be that hard to fix, let me get a PR ready this evening/night.

**Comment by capaj** [comment]
@m-a-r-c-e-l-i-n-o try it with 0.5.7, it worked out for me-I tried it with JSPM jspm@0.16.33

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Working beautifully.
