### ISSUE TITLE
Why ignore unknown module error?

### ISSUE THREAD

**Issue by peteruithoven** [capaj/systemjs-hot-reloader#80]
When `getModuleRecord` results in an error this error isn't logged, why? 
https://github.com/capaj/systemjs-hot-reloader/blob/master/hot-reloader.js#L212-L215
Would be useful to add a bit more comments to why this isn't logged. 

I just spend half an hour trying to figure out why a module wasn't hot reloading and this error would have been very useful.

**Comment by alexisvincent** [comment]
Better error handling is coming in `systemjs-hmr`
