### ISSUE TITLE
Importers not initialized when ES6 transpilation is disabled

### ISSUE THREAD

**Issue by mpfau** [capaj/systemjs-hot-reloader#81]
I noted, that the importers (in System.loads) are only initialized for the modules that are loaded before my initial System.import, when ES6 transpilation is disabled as follows:

``` js
        System.babelOptions = {
            es2015: false
        }
```

As a workaround, you can invoke pushImporters after importing your initial module:

``` js
            return System.import('test/gui/playground.js').then(function() {
                // we need to pushImporters if we disable es6 transpilation
                System.hotReloader.pushImporters(System.loads, true)
            })
```

It looks like pushImporters is called to early (constructor of HotReloader)

**Comment by alexisvincent** [comment]
Fixed in `systemjs-hmr` I think
