### ISSUE TITLE
Please we need a working example for Angular 2, current example doesn't work... 

### ISSUE THREAD

**Issue by born2net** [capaj/systemjs-hot-reloader#88]
Please we need a working example for Angular 2, current example doesn't work...
this project is outdated: https://github.com/capaj/jspm-ng2
and I can't get it working, I get errors about paths being wrong as well as traceur which is no longer used (installed TS) and bunch of other errors.

Any examples? Tutorials or any info on getting 0.17 jspm working with up to date angular 2 build would awesome!!!

reagrds

Sean

**Comment by capaj** [comment]
@born2net sorry, I have been busy. I have looked at it now and was able to quickly fix it in https://github.com/capaj/jspm-ng2/commit/bf2edbeb82e8faaa5e136b3071a67dfaa059ef31. Don't expect a lot of support on angular 2 from me, as I use React in my day 2 day job.

**Comment by born2net** [comment]
TX... I am trying now!

**Comment by born2net** [comment]
so I tried to move to TS, but no luck, I forked the project here:
https://github.com/born2net/jspm-ng2
and modified the config.js to load TypeScript instead but the app is angry at me know, failing with:
```
system.js:4 Uncaught (in promise) Error: TypeError: debug_1.default is not a function(…)
```
if we can get it working it would be awesome as we would have a hot-reload example with TypeScript and I will maintain it with Angular2 / TS updates

TX

Sean.
