### ISSUE TITLE
trying to get Angular2 with TypeScript and hot-reload, no luck so far...

### ISSUE THREAD

**Issue by born2net** [capaj/systemjs-hot-reloader#89]
special tx to @capaj  for the fix today on hot-reload and angular2 project...

So I tried to move to TypeScript, but no luck, I forked the project here:
https://github.com/born2net/jspm-ng2
and modified the config.js to load TypeScript instead but the app is angry at me now, failing with:

system.js:4 Uncaught (in promise) Error: SyntaxError: Unexpected token <(…)
if we can get it working it would be awesome as we would have a hot-reload example with TypeScript and I will maintain it with Angular2 / TS updates

TX

Sean.

**Comment by alexisvincent** [comment]
@born2net Please submit a failing test case to `systemjs-hmr`
