### ISSUE TITLE
importing html

### ISSUE THREAD

**Issue by Mosho1** [capaj/systemjs-hot-reloader#92]
Here:

https://github.com/capaj/systemjs-hot-reloader/blob/master/hot-reloader.js#L158

`'!text'` is appended to a hot reloaded html import before normalizing. Why is this required? I use `meta` and `loader` configuration to load html files with `plugin-text` and the load is just `path/to/view.html`, without the plugin.

**Comment by capaj** [comment]
@Mosho1 thanks for opening this issue. This was an early implementation which could handle reloading of html templates. Obsolete now, will remove the whole if statement.
