### ISSUE TITLE
When using Webstorm, removing breakpoint does not work

### ISSUE THREAD

**Issue by born2net** [capaj/systemjs-hot-reloader#93]
When using Webstorm, removing breakpoint does not work
the breakpoint
https://github.com/capaj/systemjs-hot-reloader/issues/newremains and stops at previous breakpointlocation
reference https://youtrack.jetbrains.com/issue/WEB-21917: 

I am not sure if issue is hot-reload lib or WebStorm ?!?!

regards

Sean
FYI Angular 2 Kitchen sink: https://github.com/born2net/ng2Boilerplate with hot-reload

**Comment by capaj** [comment]
I presume you're running it in Chrome. I will refer you to this comment:
https://github.com/capaj/systemjs-hot-reloader/issues/90#issuecomment-221508478

Closing for now, as I don't think there is anything in this repo we can do to solve this issue.

**Comment by born2net** [comment]
yes I am...
and by the way just wanted to THANK YOU for a great lib!!!!
regards,

Sean
