### ISSUE TITLE
Trace API

### ISSUE THREAD

**Issue by guybedford** [capaj/systemjs-hot-reloader#94]
@capaj I know the trace API in SystemJS is somewhat inconsistent that results in the need to check both `System.loads` and `System._loader.moduleRecords`.

I'm currently looking at a new approach here, by leaving `System.defined` module entries available when `System.trace` is set to true, and this will be available in the coming SystemJS release.

If you're interested in taking a look at the structure, let me know if that can handle the hot-reloading cases going forward. As I would like to deprecate `System.loads` and `System._loader.moduleRecords` in the SystemJS major release coming in the next few months.

**Comment by born2net** [comment]
thanks @guybedford for syncing with @capaj as we rely on hot-reloader heavily ...
regards

**Comment by alexisvincent** [comment]
SystemJS-HMR now uses System.defined

**Comment by alexisvincent** [comment]
I think we can close this now
